#library "FX_D2_NGPLUS"
#import "D2_NGPLUS.acs"
#include "zcommon.acs"

Script "FX_D2_MAP01_Open" Open
{
	If (CheckMapMD5 ("3c9902e376cca1e9c3be8763bdc21df5", "MAP01"))
	{
		Sector_SetPlaneReflection (1, wateralpha, 0);
		SetFogDensity (1, 400);
		Sector_SetFade (1, 45, 25, 10);
		SetFogDensity (7, 400);
		Sector_SetFade (7, 45, 25, 10);
		Line_SetTextureOffset (1, NO_CHANGE, -11.0, SIDE_FRONT, TEXFLAG_BOTTOM);
	}
}
